#!/bin/bash

echo "🚀 Simple Deployment Guide for PeoplePulse"

echo ""
echo "📋 STEP 1: Deploy Backend to Railway"
echo "====================================="
echo "1. Go to https://railway.app"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Select your repo: DevShubham07/PeoplePulse"
echo "5. Railway will detect it's a Java project"
echo "6. Add PostgreSQL database:"
echo "   - Go to your project"
echo "   - Click 'New' → 'Database' → 'PostgreSQL'"
echo "7. Set environment variables:"
echo "   - Go to your backend service"
echo "   - Click 'Variables' tab"
echo "   - Add these variables:"
echo "     SPRING_PROFILES_ACTIVE=prod"
echo "     DATABASE_URL=(Railway will set this automatically)"
echo "     DB_USERNAME=postgres"
echo "     DB_PASSWORD=(Railway will set this automatically)"
echo "     ADMIN_USERNAME=admin"
echo "     ADMIN_PASSWORD=admin123"
echo ""

echo "📋 STEP 2: Deploy Frontend to Vercel"
echo "====================================="
echo "1. Go to https://vercel.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New Project'"
echo "4. Import your repo: DevShubham07/PeoplePulse"
echo "5. Set root directory to: frontend"
echo "6. Build command: npm run build"
echo "7. Output directory: build"
echo "8. Add environment variable:"
echo "   REACT_APP_API_URL=https://your-railway-backend-url.railway.app"
echo ""

echo "📋 STEP 3: Update Frontend API URL"
echo "==================================="
echo "1. Get your Railway backend URL"
echo "2. Update frontend/src/services/api.js"
echo "3. Replace 'http://localhost:8080' with your Railway URL"
echo "4. Commit and push changes"
echo ""

echo "📋 STEP 4: Test Your Deployment"
echo "==============================="
echo "1. Test backend: curl https://your-railway-url.railway.app/api/employees"
echo "2. Test frontend: Visit your Vercel URL"
echo "3. Login with: admin / admin123"
echo ""

echo "🔗 Your Repository: https://github.com/DevShubham07/PeoplePulse"
echo "📊 Database: PostgreSQL (managed by Railway)"
echo "🌐 Frontend: Vercel"
echo "🔧 Backend: Railway"
echo ""
echo "✅ Ready to deploy! Follow the steps above." 