services:
  - type: web
    name: peoplepulse-backend
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: FRONTEND_URL
        value: https://devshubham07.github.io

databases:
  - name: peoplepulse-db
    databaseName: employee_management
