services:
  - type: web
    name: peoplepulse-backend
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    rootDir: backend
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production

databases:
  - name: peoplepulse-db
    databaseName: employee_management
